### ISSUE TITLE
Only current heading is sent in org mode

### ISSUE THREAD

**Issue by Vonfry** [karthink/gptel#476] opened 2024-11-14 05:47 UTC
**Briefly describe what you are trying to do**
Either I enable `gptel-org-branching-content` or not, only the heading with current cursor point is sent without previous responses, unless I select them in region.

If previous contents are user inputs, they can be sent.

I'm not sure it is a feature or bug, so this is a support request instead of bug report.

If `gptel-org-branching-context` is `t`, the selected region are always sent without processing hierarchical contents.

By the way, in markdown mode, the responses can be sent as expected.

**Additional context**
Emacs version: `GNU Emacs 30.0.92 (build 2, aarch64-apple-darwin23.2.0, NS appkit-2487.30 Version 14.2 (Build 23C64))
 of 2024-11-11`
Org mode version: `9.7.11`

**Comment by karthink** [comment] 2024-11-14 06:11
Are there any `GPTEL_` properties in the current heading?

**Comment by karthink** [comment] 2024-11-14 06:27
Could you do a dry-run and paste the request that's being sent? You can
access the dry run option from the transient menu after setting
gptel-expert-commands

**Comment by Vonfry** [comment] 2024-11-14 06:32
```
{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "system",
      "content": "You are a large language model living in Emacs and a helpful assistant. Respond concisely."
    },
    {
      "role": "user",
      "content": "**** Repeat your answer"
    }
  ],
  "stream": true,
  "temperature": 1.0
}
```

**Comment by karthink** [comment] 2024-11-14 06:42
Hmm, that's quite strange. For the record, can you paste the buffer text
here as well.

Also, are you on the latest commit of gptel?

**Comment by Vonfry** [comment] 2024-11-14 06:46
gptel version: `gptel-20241112.624`

```
*** hello

Hello! How can I assist you today?

**** repeat it
    

Could you please clarify what you'd like me to repeat?
```

**Comment by Vonfry** [comment] 2024-11-14 12:25
I found the reason.
The condition defined [here](https://github.com/karthink/gptel/blob/4aa6b7ca79b1548c36e593d0d68d2dfa644fa958/gptel-org.el#L200-L207) isn't passed when the first heading **at the begin of the buffer** (pos is 1).

It causes that
`start-bounds` returns correct values for each heading start points, but `end-bounds` only returns one value, the current cursor marker.
And then, [the loop](https://github.com/karthink/gptel/blob/4aa6b7ca79b1548c36e593d0d68d2dfa644fa958/gptel-org.el#L221-L224) only runs one time.

**Comment by karthink** [comment] 2024-11-14 15:47
I tried to reproduce it by using the same buffer contents as above (or as close as I can get it with the LLM's non-deterministic reply), but it appears to work fine.

> I found the reason.
> The condition defined [here](https://github.com/karthink/gptel/blob/4aa6b7ca79b1548c36e593d0d68d2dfa644fa958/gptel-org.el#L200-L207) isn't passed when the first heading at the begin of the buffer (pos is 1).
> I think the conditon should be (or (not (eq pos 1)) (org-heading-p))

This is only relevant when `gptel-org-branching-context` is set.  IIUC, it's not forming the right prompt even when `gptel-org-branching-context` is unset?

I suggest leaving `gptel-org-branching-context` as `nil` right now and testing.

**Comment by Vonfry** [comment] 2024-11-15 02:01
> I tried to reproduce it by using the same buffer contents as above (or as close as I can get it with the LLM's non-deterministic reply), but it appears to work fine.

If the first heading is at beginning of the buffer (position is 1), it is missed in prompt. But if it isn't at the beginning, it works fine for me. 

For the below contents, T1 isn't in prompt if cursor at T2. But T3 is included if cursor at T4. 
```
*** T1
**** T2
*** T3
**** T4
```
The `start-bounds` in the first case is `(... 1 1)`, and the second start bound cannot generate an `end-bounds` due to failure on `(not (and (eq pos 1) (org-at-heading-p)))`.

**Comment by karthink** [comment] 2024-11-15 02:19
Is this with `gptel-org-branching-context` set to `nil`?

**Comment by Vonfry** [comment] 2024-11-15 02:29
> Is this with gptel-org-branching-context set to nil?

it is `t`. For `nil`, it works as expected.

**Comment by karthink** [comment] 2024-11-15 02:35
It looks like this behavior depends on your version of Org.  What version of Org mode are you using?  You can run `M-x org-version`

**Comment by Vonfry** [comment] 2024-11-15 02:58
Two machine: one is `9.7.11` and the other is `9.7.16`. Both have the same issue.

**Comment by karthink** [comment] 2024-11-15 03:06
Hmm, 9.6.3 works differently.  I'll try to find a condition that works for all Org versions.

**Comment by karthink** [comment] 2024-11-15 04:59
Should be fixed, please try now.

**Closed** 2024-11-15 06:50 UTC
Labels: bug
