### ISSUE TITLE
Underscores `_` in responses are replaced by `/`

### ISSUE THREAD

**Issue by hieutkt** [karthink/gptel#40] opened 2023-04-10 04:21 UTC
Great package, and I enjoy its integration ootb with the new preview system in Org-mode that you are developing.

This issue is just a small annoyance: The underscores `_` in responses are replaced by `/`, this messes up some of the latex equation outputs:

![Screenshot from 2023-04-09 23-15-13](https://user-images.githubusercontent.com/16746470/230824879-b26ff2fe-0786-4be1-82e4-d97ff9f2665d.png)

**Comment by karthink** [comment] 2023-04-10 04:35
Ah, I should have expected this bug. I'll fix it soon.

This is unrelated but: May I ask how you moved the prompt from your main org buffer into the gptel buffer? Did you copy the selection, open a gptel buffer, then yank it and type out the rest of the prompt?

**Comment by hieutkt** [comment] 2023-04-10 04:38
Yeah I yanked it over and typed out the rest of the prompt. It would be nice (for me at least) if `gptel-send` can send the selected text to the dedicated `*ChatGPT*` buffer, instead of flooding output into the current buffer.

**Comment by karthink** [comment] 2023-04-10 04:44
> Yeah I yanked it over and typed out the rest of the prompt. It would be nice (for me at least) if `gptel-send` can send the selected text to the dedicated `*ChatGPT*` buffer, instead of flooding output into the current buffer.

![2023-04-09-042930_918x376_scrot](https://user-images.githubusercontent.com/8607532/230770018-9ce87644-6c17-44af-bd39-8c899303dce1.png)

The transient menu has this option now. You could do it in two ways:

1. Select a region, use `C-u C-c RET` (or equivalent: `gptel-send` with `prefix-arg`), then set the flag to open in an existing (`-e`) or new (`-n`) session. But you'll have to type the extra bits ("What is the intuition for this?") before you call `gptel-send`.
2. Select a region, use `C-u C-c RET` but use the "Read input from minibuffer" flag (`-r`) along with the `-e` or `-n` flag. The minibuffer will be populated with the region contents, which you can edit before sending. (It's easer to try than it is to explain)

**Comment by hieutkt** [comment] 2023-04-10 04:54
Hmm... I can't hit return to send from `gptel-menu`? Sorry I'm not very familiar with transient menus.

![image](https://user-images.githubusercontent.com/16746470/230828527-aac40655-730c-44b2-972f-fbffd95a917f.png)

**Comment by karthink** [comment] 2023-04-10 04:57
Wow that's odd. Not sure what the issue is. Does `C-m` instead of `RET` work?

**Comment by hieutkt** [comment] 2023-04-10 05:06
`C-m` worked, though I have to manually `C-x b` to the `*Chat GPT*` buffer afterward. I think a good behavior would be to jump to the session buffer where the text was sent to. 

This `RET` problem probably has some thing to do with how `evil-org-mode` keybinding works, or the shenanigans that Doom brings for `+org/dwim-at-point`. I never understood how these work 😅

**Comment by karthink** [comment] 2023-04-10 05:11
> I think a good behavior would be to jump to the session buffer where the text was sent to.

Hmm, I'm not sure jumping to the buffer is a good idea for async processes -- it can happen without warning seconds later while you're doing something else. The alternative is to jump immediately, but then it's no longer async and you're left waiting for the response to finish.

**Comment by hieutkt** [comment] 2023-04-10 05:16
Hmm I guess from the user perspective I want visual feedback that the function is indeed working. Seeing the transient menu simply disappear after `C-m` doesn't feel good for me ("Did I do it wrong?" moment). May be add a minibuffer notification? E.g. `The selected text was sent to *ChatGPT* as promt`

**Comment by karthink** [comment] 2023-04-10 05:35
I'm pushing a fix in a few minutes.

BTW, if you want a workflow not easily supported by gptel, you might also be interested in `gptel-request`. (See the [wiki](https://github.com/karthink/gptel/wiki))

**Comment by hieutkt** [comment] 2023-04-10 05:41
I'll look into it later. For now the switch-to-session-buffer-and-type has been mostly satisfactory for me.

Thanks for the fast reponse to this issue!

**Comment by karthink** [comment] 2023-04-10 06:00
Added more visual feedback in 00abbf75.

I'll fix the parsing issue `_` --> `/` when I can, it's a little trickier than expected.

**Comment by karthink** [comment] 2023-06-23 22:17
> I'll fix the parsing issue _ --> / when I can, it's a little trickier than expected.

I've fixed this for the specific examples you mention -- i.e. text between `\( ... \)` or `\[ ... \]` delimiters). I'm afraid there's no simple way of fixing this in general, for example with text inside `$...$` or `\begin{env} ... \end{env}`, short of implementing a full markdown parser.

I haven't pushed this change yet, still looking for a better solution.

**Comment by karthink** [comment] 2024-01-28 22:37
Should be fixed now.

**Closed** 2024-01-28 22:36 UTC
Labels: bug
