### ISSUE TITLE
gptel-default-mode does not detect markdown-mode availability

### ISSUE THREAD

**Issue by PerMildner** [karthink/gptel#109] opened 2023-10-03 20:01 UTC
`gptel-default-mode` gets set to `text-mode` for me.

I think what happens is:
```
(defcustom gptel-default-mode (if (featurep 'markdown-mode)
                               'markdown-mode
                             'text-mode)
...
)
```
But, since `markdown-mode` is autoloaded, it is not until you call `markdown-mode` that its file will be loaded, and not until then is the last line of `markdown-mode.el` executed:
```
(provide 'markdown-mode)
```
so `(featurep 'markdown-mode)` will be false until `markdown-mode` is called (and thus `markdown-mode.el` is loaded).

Possible fix: change `(featurep 'markdown-mode)` to `(fboundp 'markdown-mode)`.

**Comment by karthink** [comment] 2023-10-03 21:50
Fixed in 648fa228, thanks for catching this!

`fboundp` should work as intended.

**Closed** 2023-10-12 02:56 UTC
