### ISSUE TITLE
Can not get Gemini working

### ISSUE THREAD

**Issue by rwilson-lib** [karthink/gptel#422] opened 2024-10-14 13:41 UTC
(setq-default gptel-default-mode 'org-mode
  	              gptel-post-response-functions #'gptel-end-of-response
  	              gptel-model "gemini-pro" ; Pick your default model
                  gptel-backend (gptel-make-gemini "Gemini"
                                  :key (gptel-api-key-from-auth-source "generativelanguage.googleapis.com")
                                  :stream t)))

Here is the error that I am getting
gptel-curl-get-response: Wrong type argument: json-value-p, :text

**Comment by karthink** [comment] 2024-10-14 17:02
Can you generate a backtrace? `M-x toggle-debug-on-error`, then produce the error.

**Comment by CaptainBloodz** [comment] 2024-10-15 00:35
Possibly connected...

Just installed git master

(setq-default
;; gptel-post-response-functions #'gptel-end-of-response
 gptel-model 'gemini-1.5-flash
 gptel-backend (gptel-make-gemini "Gemini-1.5-flash"
								 :key "XXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYYZZZZZZ"
								 :stream t)

Sequence from emacs start:

M-x gptel
Minibuffer: */0    Create or choose gptel buffer (default *Gemini-1.5-flash*):[RET]

Frame opens:
Gemini-1.5-flash Ready [Ignoring media][Prompt: default][gemini-1.5-flash]
###

Typing in:
Gemini-1.5-flash Ready [Ignoring media][Prompt: default][gemini-1.5-flash]
### What is EMACS?

M-x toggle-debug-on-error
Minibuffer: Debug on error enabled globally

C-c RET

Debugger entered--Lisp error: (wrong-type-argument json-value-p :text)
  gptel-curl--get-args((:contents [(:role "user" :parts [:text "What is EMACS?"])] :safetySettings [(:category "HARM_CATEGORY_HARASSMENT" :threshold "BLOCK_NONE") (:category "HARM_CATEGORY_SEXUALLY_EXPLICIT" :threshold "BLOCK_NONE") (:category "HARM_CATEGORY_DANGEROUS_CONTENT" :threshold "BLOCK_NONE") (:category "HARM_CATEGORY_HATE_SPEECH" :threshold "BLOCK_NONE")] :system_instruction (:parts (:text "You are a large language model living in Emacs and a helpful assistant. Respond concisely.")) :generationConfig (:temperature 1.0)) "ae0191d6963c5608a12d627874e6f23b")
  gptel-curl-get-response((:data (:contents [(:role "user" :parts [:text "What is EMACS?"])] :safetySettings [(:category "HARM_CATEGORY_HARASSMENT" :threshold "BLOCK_NONE") (:category "HARM_CATEGORY_SEXUALLY_EXPLICIT" :threshold "BLOCK_NONE") (:category "HARM_CATEGORY_DANGEROUS_CONTENT" :threshold "BLOCK_NONE") (:category "HARM_CATEGORY_HATE_SPEECH" :threshold "BLOCK_NONE")] :system_instruction (:parts (:text "You are a large language model living in Emacs and a helpful assistant. Respond concisely.")) :generationConfig (:temperature 1.0)) :buffer #<buffer *Gemini-1.5-flash*> :position #<marker at 19 in *Gemini-1.5-flash*>) nil)
  gptel-request(nil :stream t)
  #<subr gptel-send>(nil)
  gptel-org--send-with-props(#<subr gptel-send> nil)
  apply(gptel-org--send-with-props #<subr gptel-send> nil)
  gptel-send(nil)
  funcall-interactively(gptel-send nil)
  command-execute(gptel-send)


From terminal command line:

curl -H 'Content-Type: application/json' -d '{"contents":[{"parts":[{"text":"What is EMACS?"}]}]}' -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=XXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYYZZZZZZ'
{
  "candidates": [
    {
      "content": {
        "parts": [
          {
            "text": "**Emacs** is a **text editor** and **integrated development environment (IDE)** known for its **extensibility**, **customizability**, and **power**. \n\nHere's a breakdown of its key features:\n\n**Features:**\n\n* **Extensible:** Emacs is highly extensible, meaning users can add new features and functionalities through its built-in scripting language, **Emacs Lisp**. This allows for customization to suit individual needs and workflows.\n* **Customizable:** Emacs provides a wide range of options for customizing its appearance, key bindings, and behavior. Users can configure everything from the color scheme to the way commands are executed.\n* **Powerful:** Emacs offers a comprehensive set of built-in features for text editing, including syntax highlighting, auto-completion, spell checking, and version control integration.\n* **Integrated Development Environment (IDE):** Emacs can be used as a full-fledged IDE for various programming languages. It provides features like debugging, code navigation, and project management.\n* **Interactive:** Emacs is highly interactive, allowing users to control and modify the editing environment in real-time.\n* **Cross-Platform:** Emacs runs on various operating systems, including macOS, Linux, Windows, and Unix.\n\n**Key Concepts:**\n\n* **Emacs Lisp:** Emacs's built-in scripting language, used for extending and customizing the editor.\n* **Major Modes:**  Special modes tailored to specific programming languages or file types, providing specialized features.\n* **Minor Modes:**  Smaller, more specific functionalities that can be activated or deactivated as needed.\n* **Packages:** Collections of Emacs Lisp code that provide new features or functionalities.\n\n**History:**\n\nEmacs was originally developed by Richard Stallman in the early 1970s. Its name stands for \"Editor MACroS.\" It has evolved over the years, with different versions developed by various groups. The two main versions are **GNU Emacs** (the official version) and **XEmacs**.\n\n**Use Cases:**\n\n* **Software development:** Emacs is widely used by programmers for coding in various languages.\n* **Text editing:** It is a powerful tool for general-purpose text editing tasks, such as writing documents, emails, and scripts.\n* **Scientific computing:** Emacs is used in scientific fields for data analysis, modeling, and visualization.\n* **Customization:** Emacs's extensibility makes it ideal for users who want to tailor their editing environment to their specific needs.\n\n**Learning Curve:**\n\nEmacs has a reputation for having a steep learning curve due to its extensive customization options and complex key bindings. However, its community offers extensive documentation, tutorials, and resources to help users get started.\n"
          }
        ],
        "role": "model"
      },
      "finishReason": "STOP",
      "index": 0,
      "safetyRatings": [
        {
          "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_HATE_SPEECH",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_HARASSMENT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
          "probability": "NEGLIGIBLE"
        }
      ]
    }
  ],
  "usageMetadata": {
    "promptTokenCount": 5,
    "candidatesTokenCount": 567,
    "totalTokenCount": 572
  }
}

**Comment by karthink** [comment] 2024-10-15 19:53
Thank you.  Should be fixed, please update and test.

**Comment by CaptainBloodz** [comment] 2024-10-15 20:05
Waiting for melpa sync...

**Comment by CaptainBloodz** [comment] 2024-10-15 21:06
Building here throws:

>>> Emerging (1 of 1) app-emacs/gptel-20241015.1951::local
 * gptel-20241015.1951.tar BLAKE2B SHA512 size ;-) ...                                                                                                            [ ok ]
 * Emacs version: 30.0.91
>>> Unpacking source...
>>> Unpacking ./gptel-20241015.1951.tar to /var/tmp/portage/app-emacs/gptel-20241015.1951/work
>>> Source unpacked in /var/tmp/portage/app-emacs/gptel-20241015.1951/work
>>> Preparing source in /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951 ...
 * Generating autoload file for GNU Emacs ...
Package autoload is deprecated
  SCRAPE   .
  INFO     Scraping files for gptel-autoloads.el... 
  INFO     Scraping files for gptel-autoloads.el...done                                                                                                           [ ok ]
 * Compiling GNU Emacs Elisp files ...
Checking /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/...
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-anthropic.el...

In gptel-make-anthropic:
gptel-anthropic.el:187:2: Warning: docstring wider than 80 characters
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-autoloads.el...
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-context.el...
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-curl.el...
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-gemini.el...

In end of data:
gptel-gemini.el:173:31: Warning: the function ‘gptel-context--collect-media’ is not known to be defined.
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-kagi.el...

In gptel-make-kagi:
gptel-kagi.el:136:2: Warning: docstring wider than 80 characters
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-ollama.el...

In toplevel form:
gptel-ollama.el:88:14: Warning: ‘plist-put’ on constant list (arg 1)
gptel-ollama.el:162:15: Warning: docstring wider than 80 characters
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-openai.el...

In gptel-make-openai:
gptel-openai.el:250:2: Warning: docstring wider than 80 characters
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-org.el...
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-privategpt.el...

In gptel-make-privategpt:
gptel-privategpt.el:103:2: Warning: docstring wider than 80 characters
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-rewrite.el...
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel-transient.el...
Compiling /var/tmp/portage/app-emacs/gptel-20241015.1951/work/gptel-20241015.1951/gptel.el...

In gptel--strip-mode-suffix:
gptel.el:850:14: Warning: ‘provided-mode-derived-p’ called with 4 arguments, but accepts only 2
Done (Total of 12 files compiled, 1 skipped)                                                                                                                      [ ok ]
>>> Source compiled.

Some warnings maybe of some interest to you, maybe not...

**Comment by CaptainBloodz** [comment] 2024-10-15 21:14
Testing just the same a described earlier, Messages buffer:

Send your query with C-c RET!
Starting "look" process... [7 times]
Debug on Error enabled globally
You can run the command ‘toggle-debug-on-error’ with M-x -on-er
Debug on Error enabled globally
Querying Gemini-1.5-flash...
Gemini-1.5-flash error (HTTP/2 400): Could not parse HTTP response.

**Comment by karthink** [comment] 2024-10-15 21:15
@CaptainBloodz Could you paste the query and output from the log?  `(setq gptel-log-level 'info)`, then check the `*gptel-log*` buffer.

**Comment by CaptainBloodz** [comment] 2024-10-15 21:27
{
  "gptel": "request body",
  "timestamp": "2024-10-16 00:23:12"
}
{
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "What is EMACS?"
        }
      ]
    }
  ],
  "safetySettings": [
    {
      "category": "HARM_CATEGORY_HARASSMENT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_HATE_SPEECH",
      "threshold": "BLOCK_NONE"
    }
  ],
  "system_instruction": {
    "parts": {
      "text": "You are a large language model living in Emacs and a helpful assistant. Respond concisely."
    }
  },
  "generationConfig": {
    "temperature": 1.0
  }
}
{
  "gptel": "response body",
  "timestamp": "2024-10-16 00:23:14"
}
[
  {
    "error": {
      "code": 400,
      "message": "API key not valid. Please pass a valid API key.",
      "status": "INVALID_ARGUMENT",
      "details": [
        {
          "@type": "type.googleapis.com/google.rpc.ErrorInfo",
          "reason": "API_KEY_INVALID",
          "domain": "googleapis.com",
          "metadata": {
            "service": "generativelanguage.googleapis.com"
          }
        }
      ]
    }
  }
]

**Comment by karthink** [comment] 2024-10-15 21:28
Your API key is invalid, as the message says.  Has Gemini worked for you in the past?

**Comment by CaptainBloodz** [comment] 2024-10-15 21:40
init.el snippet as follows:

(use-package gptel)
(use-package gptel-curl)
(use-package gptel-transient)
(use-package gptel-gemini)

(setq-default
;; gptel-post-response-functions #'gptel-end-of-response
;; gptel-model 'gemini-pro
 gptel-model 'gemini-1.5-flash

 gptel-backend (gptel-make-gemini "Gemini-1.5-flash"
								 :key "xxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsx"
								 :stream t)
 )

(setq gptel-log-level 'info)

That key works flawlessly from terminal command line as described earlier, I've just retested to be sure.

**Comment by fabcontigiani** [comment] 2024-10-15 21:46
Hi! I'm having this issue too, I followed the steps above and got the following output on `*gptel-log*`
<details>
<summary> Log </summary>

```
{
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "Hi!"
        }
      ]
    }
  ],
  "safetySettings": [
    {
      "category": "HARM_CATEGORY_HARASSMENT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_HATE_SPEECH",
      "threshold": "BLOCK_NONE"
    }
  ],
  "system_instruction": {
    "parts": {
      "text": "You are a large language model living in Emacs and a helpful assistant. Respond concisely."
    }
  },
  "generationConfig": {
    "temperature": 1.0
  }
}
{
  "gptel": "response body",
  "timestamp": "2024-10-15 18:36:34"
}
[
  {
    "error": {
      "code": 400,
      "message": "Developer instruction is not enabled for models/gemini-pro",
      "status": "INVALID_ARGUMENT"
    }
  }
]
```
</details>

Maybe the error message at the end is helpful.

**Comment by CaptainBloodz** [comment] 2024-10-15 21:48
Oops one char missing in key defined in init.el, silly me....
Retesting...

**Comment by CaptainBloodz** [comment] 2024-10-15 21:57
Out of curiosity, are the following warnings of any interest?
gptel-gemini.el:173:31: Warning: the function ‘gptel-context--collect-media’ is not known to be defined.
gptel-ollama.el:88:14: Warning: ‘plist-put’ on constant list (arg 1)
gptel.el:850:14: Warning: ‘provided-mode-derived-p’ called with 4 arguments, but accepts only 2

**Comment by karthink** [comment] 2024-10-15 22:45
@fabcontigiani Are you on the latest commit?  This was addressed in #396 recently.

**Comment by CaptainBloodz** [comment] 2024-10-15 23:20
> Hi! I'm having this issue too, I followed the steps above and got the following output on `*gptel-log*`
> Log
> 
> Maybe the error message at the end is helpful.

Test protocol unchanged:
Same error here with gemini-pro

Alternatively gemini-1.5-flash & gemini-1.5-pro-latest are working fine here.

**Comment by fabcontigiani** [comment] 2024-10-15 23:31
I'm using elpaca and running `M-x elpaca-info gptel` shows `installed version: 0.9.5 f35fc1d`, I think that's the latest commit, yes. 

I can confirm gemini-1.5-flash and gemini-1.5-pro-latest work fine for me too, it's only gemini-pro that has this problem, I'll use those instead. Thanks for this great package btw!

**Comment by CaptainBloodz** [comment] 2024-10-15 23:42
Although I'm a new user of online LLM services, 

These three models work fine through a curl comment line in terminal.
There must be 3 for a reason, or is it?

**Comment by karthink** [comment] 2024-10-16 00:58
Pushed another fix, please try now.

**Comment by karthink** [comment] 2024-10-16 01:05
> Out of curiosity, are the following warnings of any interest? gptel-gemini.el:173:31: Warning: the function ‘gptel-context--collect-media’ is not known to be defined. gptel-ollama.el:88:14: Warning: ‘plist-put’ on constant list (arg 1) gptel.el:850:14: Warning: ‘provided-mode-derived-p’ called with 4 arguments, but accepts only 2

Thanks, I've made a note.

**Comment by fabcontigiani** [comment] 2024-10-16 01:11
Just updated the package and is working flawlessly now! Many thanks!

**Comment by karthink** [comment] 2024-10-16 01:12
Closing, please reopen if the issues discussed in this thread aren't fixed for you.

For different errors please open a new thread.

**Closed by karthink** 2024-10-16 01:12 UTC

**Comment by CaptainBloodz** [comment] 2024-10-16 01:21
gemini-pro tested working here :)

**Comment by rwilson-lib** [comment] 2024-10-16 09:29
The bug is fixed Gemini is working with no error. Thank you guy for the support

**Comment by rwilson-lib** [comment] 2024-10-16 09:29
> Closing, please reopen if the issues discussed in this thread aren't fixed for you.
> 
> For different errors please open a new thread.

Working fine with no issues
