### ISSUE TITLE
Losing chunks of replies

### ISSUE THREAD

**Issue by jwr** [karthink/gptel#261] opened 2024-03-19 14:34 UTC
I only noticed this with Anthropic, but I am not 100% certain this applies to Anthropic only.

I get replies where often several characters are missing. I investigated, turned on logging and here is an example. In my output gptel session I see "dostępnośćwencji", while the log shows:

```
event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" dost"}    }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"ęp"}            }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"ność"}           }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" sek"}  }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"w"}            }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"enc"}               }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"ji"}    }

```

Note the missing " sek" chunk. It's there in the log, so this would indicate that we received it, but lost it afterwards.

This happens irregularly, sometimes 1-2 times per paragraph, sometimes once every several paragraphs.

This happens at least with output to a new buffer, or to a gptel session.

**Comment by karthink** [comment] 2024-03-20 00:52
Thanks, I guess the fix in #233 isn't quite complete.  I It's a timing based bug, so I'll need to set up a simulation of the streaming and try to find the right conditions to reproduce it.

**Comment by karthink** [comment] 2024-03-24 18:37
@jwr Could you try this:

Advise the stream filter as follows to capture the output (clear the scratch buffer first):
``` emacs-lisp
(defun gptel-filter-debug (_ output)
  (with-current-buffer (get-buffer-create "*scratch*")
    (insert output "\n-----\n")))

(advice-add 'gptel-curl--stream-filter :before #'gptel-filter-debug)
```

Use the Anthropic backend and reproduce the error, then paste the contents of the scratch buffer here.

Remove the advice afterwards so you can use gptel normally.
``` emacs-lisp
(advice-remove 'gptel-curl--stream-filter #'gptel-filter-debug)
```

This should help me nail down the timing to test against.

**Comment by jwr** [comment] 2024-03-25 13:50
This doesn't seem to happen as often as before, but here are some examples:

Output is "By combining anch n", should be "By combining anchored n":

```
event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" By"}               }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" combining"}         }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" anch"}           }

event: cont
-----
ent_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"ored"}        }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" n"}     }

```


Output is "the relev and accuracy", should be "the relevance and accuracy":

```
event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" the"}   }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" relev"}  }

event: conten
-----
t_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"ance"}  }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" and"}      }

event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":" accuracy"}             }

```

I hope this helps.

**Comment by CestDiego** [comment] 2024-03-29 05:58
I'm having this same issue only with claude models as well.

**Comment by jwr** [comment] 2024-03-29 08:59
Yes, this seems to happen with Haiku, Sonnet and Opus.

**Comment by karthink** [comment] 2024-03-29 21:09
Pushed a commit (26326c30), please check if this is fixed now.

**Comment by jwr** [comment] 2024-03-30 16:35
I am no longer able to reproduce the problem 🙂🙏 Thank you!

**Closed** 2024-03-30 16:38 UTC

**Comment by benthamite** [comment] 2024-04-19 20:32
Unfortunately, I am experiencing this same issue, despite having updated to the latest commit (#70889ad). Attached are the contents of the *scratch* buffer, after following the instructions in [this comment](https://github.com/karthink/gptel/issues/261#issuecomment-2016897282) above.
[scratch.txt](https://github.com/karthink/gptel/files/15045427/scratch.txt)

**Comment by karthink** [comment] 2024-04-20 19:24
@benthamite thanks for the data.  Do you have the text as it is inserted into your buffer?  I'd like to know _exactly_ which chunk was missed.

**Comment by benthamite** [comment] 2024-04-20 19:33
@karthink, yes, I saved the `gptel` buffer, which you can find below. (The file is zipped because GitHub didn't allow me to upload the `org-mode` file.)

In the example above, the truncated sentence is 

```
Pero cuando encuentres algo que teté amargando, detente.
```

I think the full full sentence should have been

```
Pero cuando encuentres algo que te esté amargando, detente.
```

[alegremente-claude-translate.org.zip](https://github.com/karthink/gptel/files/15049490/alegremente-claude-translate.org.zip)

**Comment by benthamite** [comment] 2024-04-20 19:34
(There are other examples. I can list them if that helps.)

**Comment by karthink** [comment] 2024-12-22 18:42
Has this happened recently?  I think we can close this otherwise.

**Comment by jwr** [comment] 2024-12-22 19:28
Not the originally reported problem, but I have been getting truncated responses from Anthropic Claude recently. I haven't had the time to pursue, debug or report it, but I thought I'd let you know as a data point.

This time the behavior was different, though: responses were clearly truncated at the end. E.g. I would get 2000 characters and then the reply would end abruptly with the last 200 or so missing.

Again, just a data point, please feel free to ignore, as I am unable to pursue this right now…

**Comment by karthink** [comment] 2024-12-22 20:18
@jwr Maybe you're hitting the token limit?

- You can check the log to see if this is the case.  `(setq gptel-log-level 'info)`, then check the `*gptel-log*` buffer.  In the last data chunk there should be a "stop_reason" field.
- You can try increasing `gptel-max-tokens`.  I think the Anthropic API caps it by default to 1024 tokens, although that's much more than 2000 characters.
