### ISSUE TITLE
I get wrong-type-argument lisp error when querying ChatGTP

### ISSUE THREAD

**Issue by boina** [karthink/gptel#37] opened 2023-04-08 11:47 UTC
I installed gptel package from MELPA. It's the latest version as far as I can tell (20230407.32).
I'm using with a free openai account. I'm not sure if this package works with the free account.

When I send a query I get the following error:
```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  make-overlay(38 nil)
  pulse-momentary-highlight-region(38 nil)
  gptel-curl--stream-cleanup(#<process gptel-curl> "finished\n")
```
In the message buffer I have this output:
```
gptel-curl--sentinel
Send your query with C-c RET!
Mark set
Querying ChatGPT...
HTTP/2 429: Could not parse HTTP response.
Entering debugger...
Mark set
```
I also evaluated the function in [https://github.com/karthink/gptel/issues/10#issuecomment-1463617391](url) and go this output:
```
HTTP/2 429 
date: Sat, 08 Apr 2023 11:20:35 GMT
content-type: application/json; charset=utf-8
content-length: 206
vary: Origin
x-request-id: 1d3db88ff14cfd42943bbb25cbafa753
strict-transport-security: max-age=15724800; includeSubDomains
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 7b4a1f350d0f194a-BCN
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
(a0ea421e57ee8e0ec12316d692184b48 . 376)
```
I'm running emacs 28.2 in Archlinux. curl version is 8.0.1
Although it says my quota is over I couldn't make it work a single time. Also, I'm not sure it's relevant but when I check my keys in the openai website I see that my keys were never used.

José.

**Comment by karthink** [comment] 2023-04-08 15:20
There are two issues here.

1. gptel is not capturing/displaying the quota error correctly.
2. You're not able to use your API key to get a response from OpenAI.


I'll address 1 soon. 

For 2, I'm not sure what's going on -- many users have confirmed that gptel works with a free account. Could you try `(setq gptel-stream nil)` and try, just to be sure?

**Comment by karthink** [comment] 2023-04-08 17:00
I just pushed a fix (1cd0f585) that should address the `wrong-type-argument` error.

**Comment by boina** [comment] 2023-04-08 18:09
I installed the latest version with the fix for wrong-type-argument.

When I set gptel-stream to nil and send a query to chatGTP I get this:

`ChatGPT error: You exceeded your current quota, please check your plan and billing details.`

and when I set gptel-stream to 1 I get this other message:

`ChatGPT error (HTTP/2 429): Could not parse HTTP response.`

Also, just in case some other setting from my init file could be causing some trouble I tried in a vanilla emacs but got the same error.

**Comment by karthink** [comment] 2023-04-08 18:41
> and when I set gptel-stream to 1 I get this other message:
> 
> `ChatGPT error (HTTP/2 429): Could not parse HTTP response.`

Hmm, the error message is still wrong. To be clear, gptel itself no longer throws an error, correct?

**Comment by karthink** [comment] 2023-04-08 19:25
> 1. gptel is not capturing/displaying the quota error correctly.

The error should now be identified correctly and consistently.

**Comment by boina** [comment] 2023-04-09 10:13
I have tried with a brand new account (I had my own from openai before chatGPT was around) and now it works. So the problem is not the gptel package, is my account. The insufficient quota message is correct then although I don't know why. I will see if I can get an answer from openai.

Thanks for the help anyway.

**Closed** 2023-04-09 10:13 UTC

**Comment by fosskers** [comment] 2023-04-13 02:51
I'm also currently suffering from this.

**Comment by karthink** [comment] 2023-04-13 03:01
Could you provide some more detail? What error exactly do you mean?

Also, could you run

(setq gptel--debug t)

and retry? A buffer should pop up with the response from ChatGPT. That should have more information.

**Comment by fosskers** [comment] 2023-04-13 03:03
I see this in my `*Messages*` buffer:
```
ChatGPT error: (HTTP/2 429) You exceeded your current quota, please check your plan and billing details.
```
The corresponding JSON from the debug output is:
```json
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

**Comment by karthink** [comment] 2023-04-13 04:20
@fosskers This isn't a gptel bug -- I'd check on the OpenAI account webpage.

**Comment by fosskers** [comment] 2023-04-13 04:33
I added a credit card, changed the model to GPT4, and now it seems to be working. Thanks!
