### ISSUE TITLE
Claude error: (HTTP/2 400) messages: text content blocks must contain non-whitespace text

### ISSUE THREAD

**Issue by benthamite** [karthink/gptel#452] opened 2024-11-01 15:32 UTC
### Please update gptel first -- errors are often fixed by the time they're reported.

- [X] I have updated gptel to the latest commit and tested that the issue still exists

### Bug Description

Continuing the discussion here: #442.

This is an instance of the phenomenon I described there as follows:

> FWIW, I have also been experiencing this issue (with an up-to-date version of `gptel`). Strangely, in my case it is fixed by closing the org buffer and reopening the file it was visiting (NB: calling `revert-buffer` is not enough: the buffer has to be killed.)

### Backend

Anthropic

### Steps to Reproduce

1. Open the attached Markdown file.
2. Search for `<`.
3. Delete the text enclosed in `<` and `>`.
4. Invoke `gptel-send`.

It may be hard to reproduce the issue since, as noted, reopening the file fixes it. Hopefully, the other attached files will provide additional hints as to what may be going on. These fils capture the output of a dry run either before or after the fix.

### Additional Context

GNU Emacs 30.0.91 (build 1, aarch64-apple-darwin24.0.0, NS appkit-2566.00 Version 15.0.1 (Build 24A348)) of 2024-10
macOS Sequoia

[Archive.zip](https://github.com/user-attachments/files/17601216/Archive.zip)
[syntax-errors.md](https://github.com/user-attachments/files/17601266/syntax-errors.md)

**Comment by gregoryg** [comment] 2024-11-05 01:13
I get this all the time with Claude, never with OpenAI.  It's always mystifying, but I'll try to get a reproducible test for you!

**Comment by benthamite** [comment] 2024-11-10 11:54
This finally happened again, though this time it doesn’t go away when I reopen the buffer. After some testing, it appears to problem occurs only when `gptel-mode` is activated. So it may be that the phenomenon I observed previously was due to the fact that closing the buffer and reopening the file had the effect of turning off `gptel-mode`.

Relevant files attached.

**Comment by benthamite** [comment] 2024-11-12 13:31
Here’s another example of what I believe is the same phenomenon. I’m not entirely sure since the error message is slightly different:

``` 
Claude error: (HTTP/2 400) messages: final assistant content cannot end with trailing whitespace
```

[files.zip](https://github.com/user-attachments/files/17717289/Archive.2.zip)

**Comment by karthink** [comment] 2024-11-20 21:22
> Here’s another example of what I believe is the same phenomenon. I’m not
> entirely sure since the error message is slightly different:
> 
> ``` 
> Claude error: (HTTP/2 400) messages: final assistant content cannot end with trailing whitespace
> ```
> 
> [ETA: uploading a new set of files, which isolate the issue better]
> 

Before I try to debug this, I want to be sure that the state was captured correctly.  Here's the prompt I get if I open up your markdown file, run gptel-mode, and place the cursor at the end of the file (before the local variables block):

`````emacs-lisp
(:model "claude-3-5-sonnet-20241022" :stream t :max_tokens 1024 :messages
 [(:role "user" :content "### I have created a model in Squiggle, an estimation programming language (code attached):")
  (:role "assistant" :content "```squiggle
<squiggle code block generated by assistant here>
```
")
  (:role "user" :content "Can you please revise it to avoid having to hardcore `")
  (:role "assistant" :content "langWeights")
  (:role "user" :content "`? You could use something like this:")
  (:role "assistant" :content "
```squiggle
// Create the base distribution for number of languages
languageDist = normal({ mean: 8, stdev: 1 })

// Calculate probability weights for each number 1-10
// We need to calculate P(x <= 1.5) for 1, P(1.5 < x <= 2.5) for 2, etc.
langWeights = [
  cdf(languageDist, 1.5),  // P(x <= 1.5)
  cdf(languageDist, 2.5) - cdf(languageDist, 1.5),
  cdf(languageDist, 3.5) - cdf(languageDist, 2.5),
  cdf(languageDist, 4.5) - cdf(languageDist, 3.5),
  cdf(languageDist, 5.5) - cdf(languageDist, 4.5),
  cdf(languageDist, 6.5) - cdf(languageDist, 5.5),
  cdf(languageDist, 7.5) - cdf(languageDist, 6.5),
  cdf(languageDist, 8.5) - cdf(languageDist, 7.5),
  cdf(languageDist, 9.5) - cdf(languageDist, 8.5),
  1 - cdf(languageDist, 9.5)  // P(x > 9.5)
]

// Test output
{langWeights, sumOfWeights: Number.sum(langWeights)}
```

")]
 :system "<My system message here>" :temperature 1.0)
`````

Does this look correct to you?

**Comment by benthamite** [comment] 2024-11-20 21:46
What I see when I place the cursor at the end of the file (before the local variables block) and run `gptel-menu` followed by `I` (`Inspect query (Lisp)`) differs from what you shared. I am not sure if these differences are significant. Here's what I see:

````emacs-lisp
(:model "claude-3-5-sonnet-20241022" :stream t :max_tokens 1024 :messages
	[(:role "user" :content
		[(:type "text" :text
			"I have created a model in Squiggle, an estimation programming language (code attached):")])
	 (:role "assistant" :content "```squiggle
// First, create an array of language data structures
languages = [
  {name: \"ja\", adjust: Dist.truncateLeft(lognormal({ mean: 0.0711, stdev: 0.05 }), 0.0001)},
  {name: \"ru\", adjust: Dist.truncateLeft(lognormal({ mean: 0.0693, stdev: 0.05 }), 0.0001)},
  {name: \"es\", adjust: Dist.truncateLeft(lognormal({ mean: 0.0672, stdev: 0.05 }), 0.0001)},
  {name: \"de\", adjust: Dist.truncateLeft(lognormal({ mean: 0.0642, stdev: 0.05 }), 0.0001)},
  {name: \"fr\", adjust: Dist.truncateLeft(lognormal({ mean: 0.0554, stdev: 0.05 }), 0.0001)},
  {name: \"it\", adjust: Dist.truncateLeft(lognormal({ mean: 0.0369, stdev: 0.05 }), 0.0001)},
  {name: \"pt\", adjust: Dist.truncateLeft(lognormal({ mean: 0.0187, stdev: 0.05 }), 0.0001)},
  {name: \"ar\", adjust: Dist.truncateLeft(lognormal({ mean: 0.0179, stdev: 0.05 }), 0.0001)},
  {name: \"fa\", adjust: Dist.truncateLeft(lognormal({ mean: 0.0195, stdev: 0.05 }), 0.0001)},
  {name: \"po\", adjust: Dist.truncateLeft(lognormal({ mean: 0.0172, stdev: 0.05 }), 0.0001)}
]

// Base parameters
eightyKEngagement = 160000
eightyKEquivalents = Dist.truncateLeft(normal({ mean: 1.5, stdev: 0.5}), 1)
growthAdjust = Dist.truncateLeft(lognormal({ p25: 0.15, p75: 0.6 }), 0.00001)
outlierAdjust = Dist.truncateLeft(lognormal({ p25: 0.3, p75: 0.9 }), 0.00001)
performanceAdjust = growthAdjust * outlierAdjust

// Create the base distribution first
baseEngagement = eightyKEngagement * eightyKEquivalents * performanceAdjust

// Create individual language distributions
lang1 = baseEngagement * languages[0].adjust
lang2 = baseEngagement * languages[1].adjust
lang3 = baseEngagement * languages[2].adjust
lang4 = baseEngagement * languages[3].adjust
lang5 = baseEngagement * languages[4].adjust
lang6 = baseEngagement * languages[5].adjust
lang7 = baseEngagement * languages[6].adjust
lang8 = baseEngagement * languages[7].adjust
lang9 = baseEngagement * languages[8].adjust
lang10 = baseEngagement * languages[9].adjust

// Create engagement distributions for each possible number of languages
dist1 = lang1
dist2 = lang1 + lang2
dist3 = lang1 + lang2 + lang3
dist4 = lang1 + lang2 + lang3 + lang4
dist5 = lang1 + lang2 + lang3 + lang4 + lang5
dist6 = lang1 + lang2 + lang3 + lang4 + lang5 + lang6
dist7 = lang1 + lang2 + lang3 + lang4 + lang5 + lang6 + lang7
dist8 = lang1 + lang2 + lang3 + lang4 + lang5 + lang6 + lang7 + lang8
dist9 = lang1 + lang2 + lang3 + lang4 + lang5 + lang6 + lang7 + lang8 + lang9
dist10 = lang1 + lang2 + lang3 + lang4 + lang5 + lang6 + lang7 + lang8 + lang9 + lang10

// Calculate weights based on normal distribution with mean 8, stdev 1
// These weights represent approximate probabilities of each number of languages
langWeights = [
  0.01, // 1 language - very unlikely
  0.02, // 2 languages
  0.05, // 3 languages
  0.09, // 4 languages
  0.12, // 5 languages
  0.15, // 6 languages
  0.18, // 7 languages
  0.19, // 8 languages - peak
  0.12, // 9 languages
  0.07  // 10 languages
]

// Final distribution using mixture with fixed weights
totalEngagement = mixture(
  [dist1, dist2, dist3, dist4, dist5, dist6, dist7, dist8, dist9, dist10],
  langWeights
)

totalEngagementPlot = Plot.dist(
  totalEngagement,
  {
    xScale: Scale.symlog(
      { min: 100, max: 1000000, title: \"Aggregate engagement across selected languages\" }
    ),
    showSummary: true,
  }
)

{
  totalEngagement,
  totalEngagementPlot,
  meanNumLanguages: 8,  // approximate based on weights
  sortedLanguages: List.map(languages, {|lang| lang.name})
}
```
")
	 (:role "user" :content
		[(:type "text" :text
			"Can you please revise it to avoid having to hardcore `")])
	 (:role "assistant" :content "langWeights")
	 (:role "user" :content
		[(:type "text" :text "`? You could use something like this:")])
	 (:role "assistant" :content "
```squiggle
// Create the base distribution for number of languages
languageDist = normal({ mean: 8, stdev: 1 })

// Calculate probability weights for each number 1-10
// We need to calculate P(x <= 1.5) for 1, P(1.5 < x <= 2.5) for 2, etc.
langWeights = [
  cdf(languageDist, 1.5),  // P(x <= 1.5)
  cdf(languageDist, 2.5) - cdf(languageDist, 1.5),
  cdf(languageDist, 3.5) - cdf(languageDist, 2.5),
  cdf(languageDist, 4.5) - cdf(languageDist, 3.5),
  cdf(languageDist, 5.5) - cdf(languageDist, 4.5),
  cdf(languageDist, 6.5) - cdf(languageDist, 5.5),
  cdf(languageDist, 7.5) - cdf(languageDist, 6.5),
  cdf(languageDist, 8.5) - cdf(languageDist, 7.5),
  cdf(languageDist, 9.5) - cdf(languageDist, 8.5),
  1 - cdf(languageDist, 9.5)  // P(x > 9.5)
]

// Test output
{langWeights, sumOfWeights: Number.sum(langWeights)}
```

")
	 (:role "user" :content [])]
	:system
	"You are a large language model living in Emacs and a helpful assistant. Respond concisely."
	:temperature 1.0)

````

**Comment by karthink** [comment] 2024-11-20 21:54
> I am not sure if these differences are significant.

They're not, the differences are because you have media-tracking turned on.  The breakdown of the user/assistant roles is the same, and it does not look correct to me, in that it does not read like a conversation with an LLM.

But if they're correct,  I can move on.

> `Claude error: (HTTP/2 400) messages: final assistant content cannot end with trailing whitespace`

This error is different from the one this thread is about.  I don't think you'd run across it in course of a normal conversation.  There is no user prompt at the end of this file.

**Comment by benthamite** [comment] 2024-11-20 22:03
> There is no user prompt at the end of this file.

Mmh, you are right. I don’t know what is going on. Perhaps I failed to save the new heading containing the question that triggered the error.

Apologies. I suggest that you do not invest time looking into this. Instead, I will post another file next time I stumble upon the issue.

(Noted that it is not the same error message: I posted it anyway in case they were related. Reproducing the issue is hard so when I come across it, or something that looks like it, I feel an inclination to report it.

**Comment by karthink** [comment] 2024-11-20 22:21
> (Noted that it is not the same error message: I posted it anyway in case they were related. Reproducing the issue is hard so when I come across it, or something that looks like it, I feel an inclination to report it.)

No worries, it's useful information.  The Anthropic API is very particular about whitespace for some reason.

**Comment by ceblan** [comment] 2024-12-01 23:39
Hi @karthink , I've got this error too in a normal chat.  

I've attached the org saved session just in case it helps. The last question is the one that triggers the error.    

[TSC-patroni-cluster.zip](https://github.com/user-attachments/files/17970708/TSC-patroni-cluster.zip)

**Comment by benthamite** [comment] 2024-12-02 00:49
FYI, I can replicate @ceblan’s error, and is the same error I was getting.

**Comment by karthink** [comment] 2024-12-02 00:59
> FYI, I can replicate @ceblan’s error, and is the same error I was getting.

That's great, a reproducer really helps.  I'll look into it soon.

**Comment by karthink** [comment] 2024-12-08 01:43
I've pushed a fix.  I ran it against gptel's prompt creation test suite and it was fine, but that suite isn't comprehensive yet.  So it's possible I broke something else about how the prompt is created for Anthropic APIs.  Please test by examining the dry-run output.

**Comment by benthamite** [comment] 2024-12-08 11:41
Unfortunately, after updating `gptel` (commit `0a8917a`) and restarting Emacs, I get the same error when running `gptel-send` at the end of @ceblan’s file. Are you not getting this error?

**Comment by karthink** [comment] 2024-12-08 23:10
@benthamite one more attempt.  Hopefully caught the bug this time.

**Comment by benthamite** [comment] 2024-12-09 00:50
Great, it works!

Closing the issue. I’ll reopen if the problem recurs or notice any unwanted side effects of the fix.

**Closed** 2024-12-09 00:50 UTC
Labels: bug

**Comment by vbichkovsky** [comment] 2025-02-06 11:32
Perhaps it's not the right place to report this, but at least gave me the clue about my situation. Usually I don't bother having a dedicated buffer for chats, but rather type where I am, such as in the *scratch* buffer. Which works properly for models such as GPT-4o. But when I switch to Claude (3.5 sonnet) it sometimes just produces an empty output. I managed to make it work again by changing mode to 'gptel-mode' for my scratch buffer and using '***' before my prompt. Is this sensitivity an expected behavior for Claude?

**Comment by justinweiss** [comment] 2025-03-06 17:58
I've started seeing this again much more often with Sonnet 3.7 and tool use in Markdown mode. Sonnet will occasionally return a single message that contains a content block with text: `\n\n` alongside the tool use call, and then fail when that is sent back as part of the next message. For example:

```
    {
      "role": "assistant",
      "content": [
        {
          "type": "text",
          "text": "\n\n"
        },
        {
          "type": "tool_use",
          "id": "toolu_bdrk_01JbCdLg88iN6fdkzncEceaD",
          "name": "open_file",
          "input": {
            "filepath": "app/models/user.rb"
          }
        }
      ]
    },
```

I've noticed that the assistant role often adds 2-4 `\n`s at the beginning of each message in its response, which probably makes this whitespace extra likely.
